spring:
   application:
        name: film-service
   profiles: dev,test,uat,production
---

spring:
   profiles : dev
   datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: dvdrental
    password: dvdrental
    driver-class-name: oracle.jdbc.OracleDriver
